// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAePuJ6GXVkbYIiVxAyEaYQn4qqK5dEc9k',
    appId: '1:939273834298:web:a366f5ed0a2d48bf698a03',
    messagingSenderId: '939273834298',
    projectId: 'aurum-tontine',
    authDomain: 'aurum-tontine.firebaseapp.com',
    storageBucket: 'aurum-tontine.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB57we2FCjPJeIohoc7e60Q_-tiA9ucF7s',
    appId: '1:939273834298:android:fd86b12d7d366879698a03',
    messagingSenderId: '939273834298',
    projectId: 'aurum-tontine',
    storageBucket: 'aurum-tontine.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8t-GR8_DGBcqUXBu7KEzrx8sn3c5ypKc',
    appId: '1:939273834298:ios:01a48de75ebc2513698a03',
    messagingSenderId: '939273834298',
    projectId: 'aurum-tontine',
    storageBucket: 'aurum-tontine.firebasestorage.app',
    iosBundleId: 'com.aurum.tontine.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8t-GR8_DGBcqUXBu7KEzrx8sn3c5ypKc',
    appId: '1:939273834298:ios:01a48de75ebc2513698a03',
    messagingSenderId: '939273834298',
    projectId: 'aurum-tontine',
    storageBucket: 'aurum-tontine.firebasestorage.app',
    iosBundleId: 'com.aurum.tontine.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAePuJ6GXVkbYIiVxAyEaYQn4qqK5dEc9k',
    appId: '1:939273834298:web:7f44757a50f4290d698a03',
    messagingSenderId: '939273834298',
    projectId: 'aurum-tontine',
    authDomain: 'aurum-tontine.firebaseapp.com',
    storageBucket: 'aurum-tontine.firebasestorage.app',
  );
}
